name = "proven_components_proof"
version = "1.0.0"
description = "Proof for reusable components."
licenses = "Apache-2.0 WITH LLVM-exception"
authors = ["Pat Rogers"]
maintainers = ["Pat Rogers <progers@classwide.com>"]
maintainers-logins = [
"pat-rogers",
]
website = "https://github.com/pat-rogers/proven_components"
project-files = [
"proven_components_proof.gpr",
]
tags = [
"reuse",
"components",
"spark",
"proof",
]

[[depends-on]]
proven_components = "*"
[[pins]]
proven_components = { path = "../" }

[configuration]
generate_c = false

[configuration.values]
proven_components.Profile = "Full"

# To be restored when a cross-compiler at 16 or later reaches the Alire index
# [[depends-on]]
# sparklib = "^16.1.0"
#
# [gpr-set-externals]
# SPARKLIB_BUILD = "Production"
