name = "proven_components_proof"
version = "1.0.0"
description = "Proof for reusable components."
licenses = "Apache-2.0 WITH LLVM-exception"
authors = ["Pat Rogers"]
maintainers = ["Pat Rogers <progers@classwide.com>"]
maintainers-logins = [
"pat-rogers",
]
website = "https://github.com/pat-rogers/proven_components"
project-files = [
"proven_components_proof.gpr",
]
tags = [
"reuse",
"components",
"spark",
"proof",
]

[[depends-on]]
proven_components = "*"
[[pins]]
proven_components = { path = "../" }

[configuration]
generate_c = false

[configuration.variables]
Profile ={type = "Enum", values = ["Full", "Embedded"], default = "Full"}
# [[depends-on]]
# sparklib = "^15.1.0"
